# Generated by Django 4.1.7 on 2023-03-25 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_alter_category_table_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'managed': True, 'verbose_name': 'item', 'verbose_name_plural': 'items'},
        ),
        migrations.AlterModelTable(
            name='item',
            table='',
        ),
    ]
